spring.application.name=tweet-fetcher

spring.datasource.url=jdbc:h2:file:./data/tweetdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

twitter.user.id=${TWITTER_USER_ID}
twitter.consumer.key=${TWITTER_CONSUMER_KEY}
twitter.consumer.secret=${TWITTER_CONSUMER_SECRET}
twitter.token.key=${TWITTER_TOKEN_KEY}
twitter.token.secret=${TWITTER_TOKEN_SECRET}

kafka.topic.tweets=tweet-fetcher-tweets

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=com.fada.tweetfetcher.serializer.TweetSerializer